from tkinter import *
from tkinter import ttk
import pylab
import time
from timeit import default_timer as timer
from datetime import timedelta

start = timer()

# start = time.time()



# To run this application, you need to install Python together with


# INPUT
# >>> seq1 = DNA("GGTCTTCGCTAGGCTTTCATCGGGTTCGGCATCTACTCTGAGTTACTACG")
# >>> seq2 = DNA("GGTCTTCAGGCTTTCATCGGGAACGGCATCTCTGAGTTACTACC")

# !!!!!IF don't want UI !!!!!!!
# use This

window = 1
seq_one = "TCCGTCAATTTCAGCCCTCTTATCCTCGGCGTTATGTGTCAAATGGCGTAGATCTGGATTGACTGTATGACGGTACCTGCTGATCGGTAGGGAGACCGAGAATCTATCGGGCTATGTCACTAAAACTTTCCAAACGCCCCGTGTCGATACTGAACGAATCGATGCACGCTCCCTTCCTTGAAAACGCATAAACATACAAGTGGGCAGATGATGCGTACGCCCCTCTAATACATCCAACACTCTACGCCCTCTTCAAGAGCTGGAAGGGCACCCTGCACTTGGATAGGGGATTATCTCGTAAGGCAAGCTCGTACCGTCATTCATGCGGAAGAGTTAACACGATTGGAAGTAGGGATAGTTTCGAACCTCGGTTACTAGTCCTAATAAGGGAACGCTGTCTGAAGGATGAGTGTCAGCCAGTGTAACCCGATGAGCTACCCAGTAGTCGAACTGGGCCAGACAACCCGGCGCTAATGCACTCAATCCCGAGGCCTGACGCGACATATCAGCTAAGAGTAGGCCGGGGGTGTAGACCTTTGGGGTTGAATAAATCTATTGTACTAATCGGCTTCAACGTGCCGCACGGGTGGCACCTCAGGAGGGGCCCACAGGGAGGAAGTAAACTGCTATTCGTCGCCGATGGTGGTAACTAATTATGTTCCTTGCCACTACAATTGTATCTAAGCCGTGTAATGAGAACATCCACACCTTAGTGAATCGATGCGCCGCTTCGGAATACCGTTTTGGCTACCTGTTACTAAGCCCATCGCGATTTTCAGGTATCGTGCACGTAGGGTTGCACCGCACGCATGTCGAACTGGTGGCGAAGTACGATTCCACGACCGGTGTACGATTCAACTACGCGGACGTGACGAGCTTCTTATATATGCTTCGCCCGCCGGACCGGCCTCGTGATGGGGTAGCTGCGCATGAGCTTATGACAAATAACGAGTGTGTACTTGTTTAATCATCTCACAGTGAAAGTCGGGAGAATAGGAGC"
seq_two = "CAGTGAAAGTCGGGAGAATAGGAGC"
data = [[(seq_one[i:i + window] != seq_two[j:j + window]) \
        for j in range(len(seq_one) - window + 1)] \
        for i in range(len(seq_two) - window + 1)]
pylab.gray()
pylab.imshow(data)
pylab.xlabel("%s (length %i bp)" % ("First sequence", len(seq_one)))
pylab.ylabel("%s (length %i bp)" % ("Second sequence", len(seq_two)))
pylab.title("Dot matrix using window size %i" % window)
end = timer()
pylab.show()
print("Time : ",timedelta(seconds=end-start))


# end = time.time()
# print("Time : ",end - start)

